# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', url: '/about'}
- {name: 'MILC', url: 'https://milc.clueboard.co/'}
- {name: 'IoT-FS', url: 'https://iot-fs.clueboard.co/'}
- {name: 'Gourd', url: 'https://github.com/clueboard/gourd'}
- {name: 'Hestia', url: 'https://github.com/clueboard/hestia'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link: 'mailto:skullydazed@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}

# Customize site text
pagination:
  next_page: 'Later'
  previous_page: 'Earlier'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
